name: Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.18.1'
        otp-version: '27.1.2'
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        allow-prereleases: true

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          deps
          _build
          ~/.cache/pip
          .venv
          .venv-py313
        key: ${{ runner.os }}-mix-pip-py313-${{ hashFiles('**/mix.lock', 'priv/python/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-mix-pip-py313-
          ${{ runner.os }}-mix-pip-
          ${{ runner.os }}-mix-
    
    - name: Install Elixir dependencies
      run: |
        mix deps.get
        mix compile

    - name: Setup Python test environments
      run: ./scripts/setup_test_pythons.sh

    - name: Run unit tests
      run: mix test --exclude skip_ci
    
    # Integration tests disabled due to port conflicts and process cleanup issues
    # - name: Run integration tests
    #   run: ./test/run_integration_tests.sh
    #   env:
    #     CI: true
    
    # Benchmarks disabled since they depend on integration tests
    # - name: Run benchmarks
    #   run: ./test/run_integration_tests.sh --with-benchmarks
    #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: benchmark-results
        path: |
          benchmark_results.json
          variable_benchmarks.png